[timecard.file]
path = 'timecard.csv'

[browser]
# Valid options are "chrome", "edge", "firefox", or "ie".
choice = "firefox"

[browser.webdriver]
default_wait_time = 60  # in seconds
# Only the browser choice needs to have its webdriver path set.
chrome.path = 'C:\Users\username\Downloads\chromedriver.exe'
edge.path = 'C:\Users\username\Downloads\msedgedriver.exe'
firefox.path = 'geckodriver.exe'
ie.path = 'C:\Users\username\Downloads\IEDriverServer.exe'

[secrets.file]
path = 'secrets.toml'
